# Generated by Django 4.2.7 on 2024-01-22 16:49

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('Enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='certificate',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed')], default='started', max_length=50),
        ),
    ]
